import { Level } from './quantumgame'

export const LEVELS = [
  new Level({
    name: '1 - Initialisation and Measurement',
    cols: 12, rows: 8,
    sources: [{ col: 0, row: 4, dir: 'right' }],
    ions: [{ col: 11, row: 4 }],
    goal: '|0⟩',
    winCondition: 'normal',
    hint: 'Press reset to initialise the ion, then measure it',
    showResetButton: true,
    preInitialized: false,
    popups: [
      { title: 'Unknown State', text: 'The ion is in an unknown quantum state. It needs to be reset to a ground state. In laboratory settings, this is typically achieved through optical pumping.', trigger: 'onLoad' },
      { title: 'Your Goal', text: 'Notice the goal box at the top of the screen. We need to measure the ion in the ground state |0⟩.', trigger: 'onLoad' },
      { title: 'Step 1', text: 'Click the Reset button to initialise the ion to the ground state |0⟩.', trigger: 'onLoad' },
      { title: 'Step 2', text: 'Click the Measure button to read out the state of the ion.', trigger: 'onReset' }
    ]
  }),
  new Level({
    name: '2 - Reflection',
    cols: 12, rows: 8,
    sources: [{ col: 0, row: 4, dir: 'right' }],
    ions: [{ col: 11, row: 4 }],
    walls: [{ col: 6, row: 3 }, { col: 6, row: 4 }, { col: 6, row: 5}],
    goal: '|0⟩',
    winCondition: 'normal',
    hint: 'Place mirrors to route the laser around the wall and hit the ion',
    showResetButton: true,
    preInitialized: false,
    popups: [
      { title: 'How to Place Mirrors', text: 'Left-click on the grid to place or rotate mirrors. Right-click to remove them. Route the beam to the ion and press Reset.', trigger: 'onLoad' },
      { title: 'How to Place Mirrors', text: 'Route the laser around the wall to hit the ion. The colour of the wall indicates what laser it blocks (red blocks all)', trigger: 'onLoad' },
      { title: 'Measure', text: 'Measure the ion to complete the level.', trigger: 'onLaserToIon' }
    ]
  }),
  new Level({
    name: '3 - The X-Gate',
    cols: 12, rows: 8,
    sources: [{ col: 0, row: 4, dir: 'right' }],
    ions: [{ col: 11, row: 4 }],
    walls: [{ col: 6, row: 3, type: 'cyan' }, { col: 6, row: 4, type: 'cyan' }, { col: 6, row: 5, type: 'cyan' }, { col: 6, row: 2, type: 'cyan' },{ col: 6, row: 7, type: 'cyan' },{ col: 6, row: 6, type: 'cyan' },{ col: 6, row: 1, type: 'cyan' },{ col: 6, row: 0, type: 'cyan' },{ col: 9, row: 3, type: 'orange' },{ col: 9, row: 4, type: 'orange' },{ col: 9, row: 5, type: 'orange' }],
    availableGates: ['X'],
    goal: '|1⟩',
    winCondition: 'all-1',
    hint: 'Select the X-gate from the laser menu and measure the ion. Walls block the laser colour that they match.',
    showResetButton: false,
    preInitialized: true,
    manualLink: { label: 'Learn more about the X-Gate', sectionId: 'gate-x' },
    popups: [
      { title: 'Ion Initialised', text: 'The ion has been initialised to the ground state |0⟩ for you.', trigger: 'onLoad' },
      { title: 'The X-Gate', text: 'Click on the laser to open the laser gates menu.', trigger: 'onLoad' },
      { title: 'Apply X-Gate', text: 'Select the orange X-gate and drag it onto the laser. This will flip the qubit to |1⟩.', trigger: 'onLaserGatesOpen' }
    ]
  }),
  new Level({
    name: '4 - Reflection With The X-Gate',
    cols: 12, rows: 8,
    sources: [{ col: 0, row: 4, dir: 'right' }],
    ions: [{ col: 10, row: 4 }],
    walls: [{ col: 9, row: 3, type: 'orange' }, { col: 9, row: 4, type: 'orange' }, { col: 9, row: 5, type: 'orange' }, { col: 10, row: 5, type: 'orange' }, { col: 11, row: 5, type: 'orange' }, { col: 11, row: 4, type: 'orange' }, { col: 11, row: 3, type: 'orange' }],
    availableGates: ['X'],
    goal: '|1⟩',
    winCondition: 'all-1',
    hint: 'Apply an X-Gate and then route the orange laser to hit the ion and measure it',
    showResetButton: false,
    preInitialized: true,
    popups: [{ title: 'Measure |1⟩', text: 'Measure a state of |1⟩ from the ion', trigger: 'onLoad' }]
  }),
  new Level({
    name: '5 - Superposition',
    cols: 12, rows: 8,
    sources: [{ col: 0, row: 4, dir: 'right' }],
    ions: [{ col: 11, row: 4 }],
    availableGates: ['H'],
    goal: '|0⟩',
    winCondition: 'all-0',
    hint: 'Apply another Hadamard gate to take the ion out of superposition and measure |0⟩',
    showResetButton: true,
    preInitialized: true,
    prePlacedGates: [['H']],
    lockedGateIndices: [0],
    gateInventory: { 'H': 12 },
    manualLink: { label: 'Learn more about the Hadamard Gate', sectionId: 'gate-h' },
    popups: [
      { title: 'Superposition', text: 'The ion is already in a superposition |+⟩. We want to measure |0⟩. Can you apply another Hadamard gate to collapse the superposition back to |0⟩?', trigger: 'onLoad' }
    ]
  }),
  new Level({
    name: '6 - Hadamard Gate',
    cols: 12, rows: 8,
    sources: [{ col: 0, row: 4, dir: 'right' }],
    ions: [{ col: 11, row: 4 }],
    availableGates: ['H'],
    goal: '|+⟩',
    winCondition: 'positive-superposition',
    hint: 'Use the Hadamard gate to put the ion into a superposition, then measure to see the distribution',
    showResetButton: true,
    preInitialized: true,
    automateMeasurement: true,
    manualLink: { label: 'Learn more about superposition', sectionId: 'qm-superposition' },
    popups: [
      { title: 'Hadamard Gate', text: 'Now we want the ion in a superposition. Use the Hadamard gate to put the ion into |+⟩.', trigger: 'onLoad' },
      { title: 'Automated Measurement', text: 'We will now automatically reset and measure the ion 10 times to show the effect of superposition (roughly 50/50 split between |0⟩ and |1⟩).', trigger: 'onAutomatedStart' },
    ]
  }),
    new Level({
      name: '7 - Negative Superposition',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 4, dir: 'right' }],
      ions: [{ col: 11, row: 4 }],
      availableGates: ['X', 'H'],
      walls: [{ col: 6, row: 3 }, { col: 6, row: 4}, { col: 6, row: 5 },{ col: 6, row: 6, },{ col: 3, row: 4 },{ col: 3, row: 3 },{ col: 3, row: 2 },{ col: 11, row: 3 },{ col: 11, row: 5 }],
      goal: '|-⟩',
      winCondition: 'negative-superposition',
      hint: 'Flip the ion with an X-gate, then apply H to create |-⟩ and measure the distribution. The order of gates matters!',
      showResetButton: true,
      preInitialized: true,
      automateMeasurement: true,
      manualLink: { label: 'Learn more about phase', sectionId: 'qm-phase' },
      popups: [
        { title: 'Negative Superposition', text: 'Create a negative superposition (|-⟩)', trigger: 'onLoad' },
        { title: 'IMPORTANT', text: 'The order of gates matters! Think about the sequence in which you apply them.', trigger: 'onLoad' },
        { title: 'Automated Measurement', text: 'The ion will be automatically reset and measured 10 times to show the superposition. You will see that phase is not visible in measurement statistics.', trigger: 'onAutomatedStart' },
      ]
    }),
    new Level({
      name: '8 - Sequencing Gates',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 4, dir: 'right' }],
      ions: [{ col: 11, row: 4 }],
      availableGates: ['X', 'H'],
      goal: '|1⟩',
      winCondition: 'all-1',
      hint: 'Use 3 gates to achieve a |1⟩ state, then measure the result.',
      showResetButton: false,
      preInitialized: true,
      requiredGateCount: 3,
      lockedGateIndices: [0],
      prePlacedGates: [['X']],
      gateInventory: { 'X': 1, 'H': 2 },
      popups: [
        { title: 'Phase Matters', text: 'You must use exactly 3 laser gates total to achieve the |1⟩ state. The first X gate is locked in place.', trigger: 'onLoad' },
      ]    }),
    new Level({
      name: '9 - Sequencing Gates Pt. 2',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 4, dir: 'right' }],
      ions: [{ col: 11, row: 4 }],
      availableGates: ['X', 'H'],
      goal: '|0⟩',
      winCondition: 'all-0',
      hint: 'Apply 3 gates in sequence, then measure the result. An X-Gate will do nothing when applied to a superposition.',
      showResetButton: false,
      preInitialized: true,
      requiredGateCount: 3,
      gateInventory: { 'X': 1, 'H': 2 },
      popups: [
        { title: 'Gate Sequencing', text: 'The ion starts in |0⟩. You must use exactly 3 laser gates to produce the definite state |0⟩', trigger: 'onLoad' },
      ]
    }),
    new Level({
      name: '10 - CNOT Gate',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 4 }],
      ions: [{ col: 4, row: 4 }, { col: 8, row: 5 }],
      walls: [{ col: 5, row: 5, type: 'orange' }, { col: 5, row: 6, type: 'orange' },{ col: 5, row: 7, type: 'orange' },{ col: 5, row: 4, type: 'orange' },{ col: 5, row: 3, type: 'orange' },{ col: 5, row: 2, type: 'orange' },{ col: 5, row: 1, type: 'orange' },{ col: 5, row: 0, type: 'orange' }],
      availableGates: ['X', 'CNOT'],
      goal: '|1⟩ |1⟩',
      winCondition: 'all-1',
      hint: 'Apply X-gate to Ion A, then route C-NOT through both ions to flip Ion B',
      showResetButton: true,
      preInitialized: true,
      gateInventory: { 'X': 1, 'CNOT': 1 },
      manualLink: { label: 'Learn more about the C-NOT Gate', sectionId: 'gate-cnot' },
      popups: [
        { title: 'Objective', text: 'Read a state of |1⟩ from the 2nd ion using the new CNOT gate.', trigger: 'onLoad' },
        { title: 'Strategy', text: 'You can only reach Ion B with a CNOT laser gate (shown in green). An orange wall prevents direct access.', trigger: 'onLoad' },
        { title: 'CNOT Explained', text: 'When the 1st ion is |1⟩ and the laser hits both ions, the 2nd ion will turn to |1⟩.', trigger: 'onLaserGatesOpen' }
      ]    }),
    new Level({
      name: '11 - Entanglement (Spooky Action)',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 4 }],
      ions: [{ col: 4, row: 4 }, { col: 8, row: 4 }],
      walls: [],
      availableGates: ['H', 'CNOT'],
      goal: 'Entangle the Two Ions',
      winCondition: 'any',
      hint: 'Apply a CNOT gate to the laser to entangle the two ions.',
      showResetButton: true,
      preInitialized: true,
      lockedGateIndices: [0],
      gateInventory: { 'H': 1, 'CNOT': 1 },
      prePlacedGates: [['H']],
      requiredGateCount: 2,
      automateMeasurement: true,
      manualLink: { label: 'Learn more about entanglement', sectionId: 'qm-entanglement' },
      popups: [
        { title: 'Spooky Action at a Distance', text: 'Here we will introduce you to the concept of entanglement, where one ion\'s state determines the other.', trigger: 'onLoad' },
        { title: 'The Bell State', text: 'Ion A is in a superposition. Drag the CNOT gate onto the laser to entangle the ions so that measuring one guarantees the result of the other.', trigger: 'onLaserGatesOpen' },
        { title: 'Measurement Demo', text: 'Measuring the control results in the same value measured in the other ion! They are perfectly linked.', trigger: 'onAutomatedStart' }
      ]
    }),
    new Level({
      name: '12 - Spooky Action',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 2 }],
      ions: [{ col: 9, row: 2 }, { col: 9, row: 6 }],
      walls: [{ col: 5, row: 2, type: 'standard' }, { col: 9, row: 4, type: 'standard' }],
      availableGates: ['H', 'CNOT'],
      goal: 'Entangle the Ions',
      winCondition: 'positive-superposition',
      hint: 'Use mirrors to navigate around the walls and hit both ions in sequence.',
      showResetButton: true,
      preInitialized: true,
      gateInventory: { 'H': 1, 'CNOT': 1 },
      lockedGateIndices: [],
      requiredGateCount: 2,
      automateMeasurement: true,
      popups: [
        { title: 'Manual Entanglement', text: 'Now try it yourself! Apply the H-gate and CNOT-gate to entangle the ions manually', trigger: 'onLoad' }
      ]
    }),
    new Level({
      name: '13 - Anti-Correlation',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 2 }, { col: 8, row: 6, dir: 'up' }],
      ions: [{ col: 4, row: 2 }, { col: 8, row: 2 }],
      walls: [],
      availableGates: ['H', 'X', 'CNOT'],
      goal: 'Entangle, then invert Ion B',
      winCondition: 'any',
      hint: 'Entangle the ions first and then apply an X-gate to just Ion B (you can use Laser 2 to target just Ion B).',
      showResetButton: true,
      preInitialized: true,
      gateInventory: { 'H': 1, 'X': 1, 'CNOT': 1 },
      lockedGateIndices: [],
      requiredGateCount: 3,
      automateMeasurement: true,
      manualLink: { label: 'Learn more about Anti-Correlation', sectionId: 'qm-anticorrelation' },
      popups: [
        { title: 'Anti-Correlation', text: 'Entangled states can be modified locally. See what happens when you apply an X-gate to one half of an entangled pair.', trigger: 'onLoad' },
        { title: 'Measurement Demo', text: 'The results are perfectly opposite (strictly 0,1 or 1,0). Applying the X-gate inverted their relationship while preserving the entanglement.', trigger: 'onAutomatedStart' }
      ]
    }),

    new Level({
      name: '14 - Uncomputing',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 4 }],
      ions: [{ col: 4, row: 4 }, { col: 8, row: 4 }],
      walls: [],
      availableGates: ['H', 'CNOT'],
      goal: '|0⟩ |0⟩',
      winCondition: 'all-0',
      hint: 'Apply gates in the exact reverse order to uncompute the entanglement.',
      showResetButton: true,
      preInitialized: true,
      prePlacedGates: [['H', 'CNOT']],
      lockedGateIndices: [0, 1],
      gateInventory: { 'H': 2, 'CNOT': 2 },
      requiredGateCount: 4,
      automateMeasurement: false,
      manualLink: { label: 'Learn more about Uncomputing', sectionId: 'qm-uncomputing' },
      popups: [
        { title: 'Uncomputing', text: 'Quantum operations are reversible. If you perform an operation, you can undo it by applying the same operations in reverse order.', trigger: 'onLoad' },
        { title: 'The Challenge', text: 'Can you reverse the operation to return the system to |0⟩ |0⟩?', trigger: 'onLaserGatesOpen' }
      ]
    }),
    new Level({
      name: '15 - Swapping States',
      cols: 12, rows: 8,
      sources: [{ col: 1, row: 2 }, { col: 1, row: 6 }],
      ions: [{ col: 3, row: 2 }, { col: 9, row: 6 }],
      walls: [{ col: 0, row: 3, type: 'green' },{ col: 1, row: 3, type: 'green' },{ col: 2, row: 3, type: 'green' },{ col: 3, row: 3, type: 'green' },{ col: 4, row: 3, type: 'green' },{ col: 5, row: 3, type: 'green' },{ col: 6, row: 3, type: 'green' },{ col: 7, row: 3, type: 'green' },{ col: 8, row: 3, type: 'green' }, { col: 9, row: 7},],
      availableGates: ['CNOT'],
      goal: '|0⟩ |1⟩',
      winCondition: '01',
      hint: 'A CNOT flips the second ion if the first ion is |1⟩. Flip ion B to |1⟩, then use the second laser to flip ion A to |0⟩.',
      showResetButton: true,
      preInitialized: true,
      prePlacedGates: [['X'], ['CNOT']],
      gateInventory: { 'CNOT': 2,'X': 1 },
      requiredGateCount: 3,
      lockedGateIndices: [0,1],
      automateMeasurement: false,
      popups: [
        { title: 'Swapping States', text: 'Can you find a way to swap the quantum states of the ions using only multi-qubit CNOT operations?', trigger: 'onLoad' },
      ]
    }),

    new Level({
      name: '16 - Triple Entangled (GHZ State)',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 2 }, { col: 0, row: 5 }],
      ions: [{ col: 3, row: 2 }, { col: 4, row: 5 }, { col: 8, row: 5 }],
      walls: [{ col: 5, row: 0, type: 'purple' }, { col: 5, row: 1, type: 'purple' }, { col: 5, row: 2, type: 'purple' }, { col: 5, row: 3, type: 'purple' }, { col: 5, row: 4, type: 'purple' }, { col: 5, row: 5, type: 'purple' }, { col: 5, row: 6, type: 'purple' }, { col: 5, row: 7, type: 'purple' }],
      availableGates: ['H', 'CNOT'],
      goal: 'Create a 3-Qubit GHZ State',
      winCondition: 'any',
      hint: 'Use Laser 1 to entangle Ion A and Ion B. Use Laser 2 to cascade the entanglement from Ion B to Ion C.',
      showResetButton: true,
      preInitialized: true,
      gateInventory: { 'H': 1, 'CNOT': 2 },
      prePlacedGates: [[], ['CNOT'],],
      lockedGateIndices: [1],
      requiredGateCount: [2, 1],
      automateMeasurement: true,
      manualLink: { label: 'Learn more about GHZ States', sectionId: 'qm-ghz' },
      popups: [
        { title: '3 Qubit Levels: The GHZ State', text: 'You now have three ions on the board. Can you entangle all of them to always collapse to the exact same correlated outcomes: either |000⟩ or |111⟩?', trigger: 'onLoad' },
        { title: 'Measurement Demo', text: 'Look at the history log! Notice how all three ions perfectly collapse to match each other every single iteration. This is a Greenberger-Horne-Zeilinger (GHZ) state.', trigger: 'onAutomatedStart' }
      ]
    }),

    new Level({
      name: '17 - Using CNOTS',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 2 }, { col: 0, row: 4 }],
      ions: [{ col: 3, row: 2 }, { col: 7, row: 4 }, { col: 11, row: 6 }],
      walls: [{ col: 0, row: 3, type: 'orange' }, { col: 1, row: 3, type: 'orange' }, { col: 2, row: 3, type: 'orange' }, { col: 3, row: 3, type: 'orange' }, { col: 4, row: 3, type: 'orange' }, { col: 5, row: 3, type: 'orange' }, { col: 6, row: 3, type: 'orange' }, { col: 7, row: 3, type: 'orange' }, { col: 8, row: 3, type: 'orange' }, { col: 9, row: 3, type: 'orange' }, { col: 10, row: 3, type: 'orange' }, { col: 11, row: 3, type: 'orange' }],
      availableGates: ['CNOT'],
      goal: '|1⟩ |1⟩ |1⟩',
      winCondition: 'all-1',
      hint: 'Route Laser 1 through A and B. Route Laser 2 through B and C.',
      showResetButton: true,
      preInitialized: true,
      prePlacedGates: [['X'], [],],
      lockedGateIndices: [0],
      gateInventory: { 'CNOT': 3, 'X': 3 },
      requiredGateCount: [2],
      automateMeasurement: false,
      popups: [
        { title: 'Cascading CNOTs', text: 'Read state |1⟩, |1⟩, |1⟩ from this system.', trigger: 'onLoad' },
      ]
    }),

    new Level({
      name: '18 - Uncomputing Three Ions',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 2 }, { col: 5, row: 2 },
      ],
      ions: [{ col: 3, row: 2 }, { col: 7, row: 2 }, { col: 9, row: 2 }],
      walls: [],
      availableGates: ['H', 'CNOT'],
      goal: '|0⟩ |0⟩ |0⟩',
      winCondition: 'normal',
      hint: 'Apply the exact inverse sequence to the exact same lasers to unravel the GHZ state.',
      showResetButton: true,
      preInitialized: true,
      prePlacedGates: [['H', 'CNOT'], ['CNOT']],
      lockedGateIndices: [0, 1, 2],
      gateInventory: { 'H': 2, 'CNOT': 4 },
      requiredGateCount: [4, 2],
      automateMeasurement: false,
      popups: [
        { title: 'Uncomputing Three Ions', text: 'These three ions are entangled together in the GHZ state you created earlier. Can you use what you know about reversible operations to return the ions to the ground state |0⟩, |0⟩, |0⟩ ?', trigger: 'onLoad' },
      ]
    }),

    new Level({
      name: '19 - Quadruple Entangled (GHZ State)',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 2 }, { col: 0, row: 4 }, { col: 0, row: 6 }],
      ions: [{ col: 3, row: 2 }, { col: 4, row: 4 }, { col: 7, row: 4 }, { col: 8, row: 6 }  ],
      walls: [],
      availableGates: ['H', 'CNOT'],
      goal: 'Create a 4-Qubit GHZ State',
      winCondition: 'any',
      hint: 'Chain the entanglement from A->B, then B->C, then C->D.',
      showResetButton: true,
      preInitialized: true,
      gateInventory: { 'H': 1, 'CNOT': 3 },
      lockedGateIndices: [],
      requiredGateCount: [2, 1, 1],
      automateMeasurement: true,
      popups: [
        { title: 'Quadruple Entangled', text: 'You now have four ions, can you entangle all of them to always read the same state (|1⟩, |1⟩, |1⟩, |1⟩) or (|0⟩, |0⟩, |0⟩, |0⟩)?', trigger: 'onLoad' },
        { title: 'Measurement Demo', text: 'All four ions collapse in perfect unison every single time. You have built a 4-qubit GHZ state.', trigger: 'onAutomatedStart' }
      ]
    }),

    new Level({
      name: '20 - Bell Pairs',
      cols: 12, rows: 8,
      sources: [{ col: 0, row: 2 }, { col: 0, row: 6 }],
      ions: [{ col: 4, row: 2 }, { col: 8, row: 2 }, { col: 4, row: 6 }, { col: 8, row: 6 } ],
      walls: [
        { col: 0, row: 4, type: 'standard' },
        { col: 1, row: 4, type: 'standard' },
        { col: 2, row: 4, type: 'standard' },
        { col: 3, row: 4, type: 'standard' },
        { col: 4, row: 4, type: 'standard' },
        { col: 5, row: 4, type: 'standard' },
        { col: 6, row: 4, type: 'standard' },
        { col: 7, row: 4, type: 'standard' },
        { col: 8, row: 4, type: 'standard' },
        { col: 9, row: 4, type: 'standard' },
        { col: 10, row: 4, type: 'standard' },
        { col: 11, row: 4, type: 'standard' },
      ],
      availableGates: ['H', 'CNOT'],
      goal: 'Two Independent Entangled Pairs',
      winCondition: 'any',
      hint: 'Create one Bell pair on the top and a separate Bell pair on the bottom.',
      showResetButton: true,
      preInitialized: true,
      gateInventory: { 'H': 2, 'CNOT': 2 },
      lockedGateIndices: [],
      requiredGateCount: [2, 2],
      automateMeasurement: true,
      manualLink: { label: 'Learn more about Bell Pairs', sectionId: 'qm-bell' },
      popups: [
        { title: 'Bell Pairs', text: 'Entanglement only exists between the specific qubits you entangle. Can you create two separately entangled pairs?', trigger: 'onLoad' },
        { title: 'Measurement Demo', text: 'Look at the results: A perfectly matches B, and C perfectly matches D. However, the two pairs operate completely independently of each other', trigger: 'onAutomatedStart' }
      ]
    })

]
